### ISSUE TITLE
Cannot set property length of [object Object] which has only a getter

### ISSUE THREAD

**Issue by tamlyn** [apparentlymart/node-angularcontext#5]
I'm having problems loading Angular. I have a simple CLI script as follows:

	var angularcontext = require('angularcontext');
	var context = angularcontext.Context();
	context.runFile('node_modules/angular/angular.js', function (res, err) {
		console.log(arguments);
	});

And when I run it I get:

```
...\node_modules\angularcontext\node_modules\jsdom\node_modules\contextify\lib\contextify.js:12
        return ctx.run.apply(ctx, arguments);
                       ^
TypeError: Cannot set property length of [object Object] which has only a getter
    at DocumentFragment.core.Node.insertBefore (...\node_modules\angularcontext\node_modules\jsdom\lib\jsdom\level1\core.js:553:30)
    at DocumentFragment.<anonymous> (...\node_modules\angularcontext\node_modules\jsdom\lib\jsdom\level2\events.js:332:20)
    at DocumentFragment.proto.(anonymous function) [as insertBefore] (...\node_modules\angularcontext\node_modules\jsdom\lib\jsdom\utils.js:23:26)
    at DocumentFragment.core.Node.appendChild (...\node_modules\angularcontext\node_modules\jsdom\lib\jsdom\level1\core.js:671:17)
    at Contextify.sandbox.run (...\node_modules\angularcontext\node_modules\jsdom\node_modules\contextify\lib\contextify.js:12:24)
    at ...\node_modules\angularcontext\lib\main.js:118:45
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

I've tried with Angular 1.3.15 and 1.2.1. JSDom is 0.8.11 and Contextify is 0.1.13.

**Comment by apparentlymart** [comment]
I couldn't reproduce your issue as you presented it.

Here's what I have installed:

```
tmp
├── angular@1.3.15
└─┬ angularcontext@0.0.17
  └─┬ jsdom@0.8.11
    ├─┬ contextify@0.1.13
    │ ├── bindings@1.2.1
    │ └── nan@1.5.3
    ├── cssom@0.3.0
    ├── cssstyle@0.2.24
    ├─┬ htmlparser2@3.8.2
    │ ├── domelementtype@1.3.0
    │ ├── domhandler@2.3.0
    │ ├─┬ domutils@1.5.1
    │ │ └─┬ dom-serializer@0.1.0
    │ │   ├── domelementtype@1.1.3
    │ │   └── entities@1.1.1
    │ ├── entities@1.0.0
    │ └─┬ readable-stream@1.1.13
    │   ├── core-util-is@1.0.1
    │   ├── inherits@2.0.1
    │   ├── isarray@0.0.1
    │   └── string_decoder@0.10.31
    ├── nwmatcher@1.3.4
    ├─┬ request@2.55.0
    │ ├── aws-sign2@0.5.0
    │ ├─┬ bl@0.9.4
    │ │ └─┬ readable-stream@1.0.33
    │ │   ├── core-util-is@1.0.1
    │ │   ├── inherits@2.0.1
    │ │   ├── isarray@0.0.1
    │ │   └── string_decoder@0.10.31
    │ ├── caseless@0.9.0
    │ ├─┬ combined-stream@0.0.7
    │ │ └── delayed-stream@0.0.5
    │ ├── forever-agent@0.6.1
    │ ├─┬ form-data@0.2.0
    │ │ └── async@0.9.0
    │ ├─┬ har-validator@1.7.0
    │ │ ├── bluebird@2.9.25
    │ │ ├─┬ chalk@1.0.0
    │ │ │ ├── ansi-styles@2.0.1
    │ │ │ ├── escape-string-regexp@1.0.3
    │ │ │ ├─┬ has-ansi@1.0.3
    │ │ │ │ ├── ansi-regex@1.1.1
    │ │ │ │ └── get-stdin@4.0.1
    │ │ │ ├─┬ strip-ansi@2.0.1
    │ │ │ │ └── ansi-regex@1.1.1
    │ │ │ └── supports-color@1.3.1
    │ │ ├─┬ commander@2.8.1
    │ │ │ └── graceful-readlink@1.0.1
    │ │ └─┬ is-my-json-valid@2.10.1
    │ │   ├── generate-function@2.0.0
    │ │   ├─┬ generate-object-property@1.1.1
    │ │   │ └── is-property@1.0.2
    │ │   ├── jsonpointer@1.1.0
    │ │   └── xtend@4.0.0
    │ ├─┬ hawk@2.3.1
    │ │ ├── boom@2.7.1
    │ │ ├── cryptiles@2.0.4
    │ │ ├── hoek@2.13.0
    │ │ └── sntp@1.0.9
    │ ├─┬ http-signature@0.10.1
    │ │ ├── asn1@0.1.11
    │ │ ├── assert-plus@0.1.5
    │ │ └── ctype@0.5.3
    │ ├── isstream@0.1.2
    │ ├── json-stringify-safe@5.0.0
    │ ├─┬ mime-types@2.0.10
    │ │ └── mime-db@1.8.0
    │ ├── node-uuid@1.4.3
    │ ├── oauth-sign@0.6.0
    │ ├── qs@2.4.1
    │ ├── stringstream@0.0.4
    │ ├── tough-cookie@1.1.0
    │ └── tunnel-agent@0.4.0
    └── xmlhttprequest@1.7.0

```

I ran your script exactly as you presented it and it printed out two sets of arguments.

This did actually lead me to finding a *different* bug, which is that the ``runFile`` method actually runs the provided file twice, due to an oversight in some earlier refactoring to generalize the interface.

We should fix the behavior of ``runFile``, but for the moment perhaps you could try using ``runMulti`` instead, which takes an array of either filenames or raw sources and runs them. Here's how your program looks with that changed:

```js
var angularcontext = require('angularcontext');
var context = angularcontext.Context();
context.runMulti(['node_modules/angular/angular.js'], function (res, err) {
    console.log(arguments);
});
```

When I run this I get the expected result:

```
$ node try.js
{ '0': true }
```

**Comment by tamlyn** [comment]
Thanks for the super speedy response!

I get the same error with `runMulti`. However upgrading jsdom to 1.0.0 seems fix the problem. I'm running node v0.12.2 if that's relevant.

**Comment by apparentlymart** [comment]
Ahh, that's the trick. I was on 0.10 because that's what I have installed on my production hosts right now.

After upgrading to 0.12.2 I can reproduce the issue as you reported it. It looks like an issue in the ancient version of jsdom that this module was pinned to.

I just made release v0.0.18 which switches to jsdom 3.1.2, and also fixes the double-execution issue that your script brought to light. Could you give that a try and see if it works for you?

**Comment by tamlyn** [comment]
Yep, that works. Thanks.
